<a href="https://colab.research.google.com/github/2303a51455/2303A51455--B07-PDS/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1st question

In [1]:
import numpy as np
A = np.random.randint(1, 11, (3, 3))
B = np.random.randint(1, 11, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)


Matrix A:
 [[7 6 5]
 [5 1 8]
 [8 7 1]]
Matrix B:
 [[7 8 5]
 [9 6 9]
 [4 2 5]]


In [3]:
add_result = np.add(A, B)
print( add_result)


[[14 14 10]
 [14  7 17]
 [12  9  6]]


In [4]:

sub_result = np.subtract(A, B)
print( sub_result)


[[ 0 -2  0]
 [-4 -5 -1]
 [ 4  5 -4]]


In [5]:

manual_add = A[0,0] + B[0,0]
manual_sub = A[0,0] - B[0,0]

print(f"Manual check for position [0,0]: {A[0,0]} + {B[0,0]} = {manual_add}")
print(f"Manual check for position [0,0]: {A[0,0]} - {B[0,0]} = {manual_sub}")


Manual check for position [0,0]: 7 + 7 = 14
Manual check for position [0,0]: 7 - 7 = 0


2nd question

In [6]:
import numpy as np
A = np.random.randint(1, 10, (3, 2))
B = np.random.randint(1, 10, (2, 3))

print("Matrix A (3x2):\n", A)
print("Matrix B (2x3):\n", B)


Matrix A (3x2):
 [[8 4]
 [7 4]
 [1 7]]
Matrix B (2x3):
 [[2 8 8]
 [8 9 5]]


In [7]:

C = np.dot(A, B)
print("Result of A x B (3x3):\n", C)


Result of A x B (3x3):
 [[ 48 100  84]
 [ 46  92  76]
 [ 58  71  43]]


In [8]:
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)
print("Shape of Result:", C.shape)


Shape of A: (3, 2)
Shape of B: (2, 3)
Shape of Result: (3, 3)


In [9]:
manual_check = A[0,0]*B[0,0] + A[0,1]*B[1,0]
print(f"Manual check for C[0,0]: {manual_check} vs {C[0,0]}")


Manual check for C[0,0]: 48 vs 48
